apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerated
  labels:
    env: test
spec: 
  containers: 
  - name: nginx
    image: nginx
  #asking for vip room
  nodeSelector:
   project: roboshop
  #showing booking information
  tolerations:
  - key: "project"
    operator: "Equal"
    value: "roboshop"
    effect: "NoExecute"